// Code generated by goctl. DO NOT EDIT.
package types

type InsertReq struct {
	Title string `json:"title"`
	Text  string `json:"text"`
}

type InsertReply struct {
	Id int64 `json:"id"`
}

type DeleteReq struct {
	Id int64 `json:"id"`
}

type DeleteReply struct {
	Rep string `json:"reponse"`
}

type FindReq struct {
	Id int64 `json:"id"`
}

type FindReply struct {
	Title string `json:"title"`
	Text  string `json:"text"`
}
