// Code generated by goctl. DO NOT EDIT!
// Source: sts.proto

package server

import (
	"context"

	"test/sts/rpc/internal/logic"
	"test/sts/rpc/internal/svc"
	"test/sts/rpc/types/sts"
)

type StsServer struct {
	svcCtx *svc.ServiceContext
	sts.UnimplementedStsServer
}

func NewStsServer(svcCtx *svc.ServiceContext) *StsServer {
	return &StsServer{
		svcCtx: svcCtx,
	}
}

func (s *StsServer) Insert(ctx context.Context, in *sts.InsertRequest) (*sts.InsertResponse, error) {
	l := logic.NewInsertLogic(ctx, s.svcCtx)
	return l.Insert(in)
}

func (s *StsServer) Delete(ctx context.Context, in *sts.DeleteRequest) (*sts.DeleteResponse, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}

func (s *StsServer) Find(ctx context.Context, in *sts.FindRequest) (*sts.FindResponse, error) {
	l := logic.NewFindLogic(ctx, s.svcCtx)
	return l.Find(in)
}
