// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"test/apimodel/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/Insert",
				Handler: InsertHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/Delete",
				Handler: DeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/Find",
				Handler: FindHandler(serverCtx),
			},
		},
	)
}
